// Single source of truth for IPC channel names.

export const IPC = {
  // renderer -> main (invoke)
  getSnapshot: 'state:get-snapshot',
  getSettings: 'settings:get',
  setSettings: 'settings:set',
  setCredentials: 'credentials:set',
  runDoctor: 'doctor:run',
  toolHealthRun: 'tool-health:run',
  linearTeams: 'linear:teams',
  linearWorkflowStates: 'linear:workflow-states',
  linearIssueCreateMeta: 'linear:issue-create-meta',
  linearCreateIssue: 'linear:create-issue',
  skillsList: 'skills:list',
  mcpServersList: 'mcp-servers:list',
  mcpLogin: 'mcp-servers:login',
  orchestratorSetEnabled: 'orchestrator:set-enabled',
  issueApprovePlan: 'issue:approve-plan',
  issueUpdatePlan: 'issue:update-plan',
  issueAnswerPlanQuestions: 'issue:answer-plan-questions',
  issuePlanFeedback: 'issue:plan-feedback',
  issueReprompt: 'issue:reprompt',
  issueAddressGhComments: 'issue:address-gh-comments',
  issueRetry: 'issue:retry',
  issueMove: 'issue:move',
  sessionStop: 'session:stop',
  sessionReadLog: 'session:read-log',
  termCreate: 'term:create',
  termCreateForIssue: 'term:create-for-issue',
  termCreateAgentForIssue: 'term:create-agent-for-issue',
  termCreateTicketDraft: 'term:create-ticket-draft',
  termList: 'term:list',
  termBuffer: 'term:buffer',
  termKill: 'term:kill',
  // renderer -> main (send, fire-and-forget: keystroke/resize hot paths)
  termWrite: 'term:write',
  termResize: 'term:resize',
  winHide: 'window:hide',
  devStart: 'dev:start',
  devStop: 'dev:stop',
  deployStart: 'deploy:start',
  deployStop: 'deploy:stop',
  reviewsSetEnabled: 'reviews:set-enabled',
  reviewStop: 'review:stop',
  reviewRetrigger: 'review:retrigger',
  errorsList: 'errors:list',
  errorsInvestigate: 'errors:investigate',
  pickFolder: 'dialog:pick-folder',
  quitConfirm: 'app:quit-confirm',
  openExternal: 'shell:open-external',
  revealFile: 'shell:reveal-file',

  // main -> renderer (send)
  evSnapshot: 'ev:snapshot',
  evIssueUpdated: 'ev:issue-updated',
  evIssueRemoved: 'ev:issue-removed',
  evSessionUpdated: 'ev:session-updated',
  evSessionOutput: 'ev:session-output',
  evReviewsUpdated: 'ev:reviews-updated',
  evDevServersUpdated: 'ev:dev-servers-updated',
  evDeploysUpdated: 'ev:deploys-updated',
  evSettingsChanged: 'ev:settings-changed',
  evToolHealth: 'ev:tool-health',
  evRateLimit: 'ev:rate-limit',
  evPlanUsage: 'ev:plan-usage',
  evNavigate: 'ev:navigate',
  evTermData: 'ev:term-data',
  evTermExit: 'ev:term-exit',
  /** ⌘W pressed — intercepted in main so the menu doesn't close the window first */
  evCloseShortcut: 'ev:close-shortcut',
  /** ⌘⇧B pressed — toggles the embedded browser panel */
  evBrowserShortcut: 'ev:browser-shortcut',
  /** ⌘B pressed — collapses/expands the sidebar */
  evSidebarShortcut: 'ev:sidebar-shortcut',
  /** ⌘T pressed — opens a new browser tab when the panel is open */
  evNewTabShortcut: 'ev:new-tab-shortcut',
  /** a quit was requested (⌘Q/menu/tray/dock) — renderer shows the confirm modal */
  evConfirmQuit: 'ev:confirm-quit'
} as const
